FROM node:20-bookworm-slim AS base

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package-lock.json ./apps/api/

RUN npm install && npm --prefix apps/api install

COPY . .

RUN npm --prefix apps/api run prisma:generate

RUN npm --prefix apps/api run build

EXPOSE 3001

CMD ["npm", "--prefix", "apps/api", "run", "start:prod"]
